### ISSUE TITLE
Support for the Social Accounts Auth?

### ISSUE THREAD

**Issue by iamkevingreen** [wojtkowiak/meteor-desktop#58] opened 2017-01-24 20:15 UTC
The way accounts-google works with meteor is it creates a popup window that it passes auth back through, and electron doesn't create a popup from the social buttons so you actually can't auth from the social networks. 

I have seen an implementation using Auth0 that inlines the google auth, but I went down this rabbit hole hoping to just tie into my existing Meteor Google Auth that I've currently been using with an existing project. 

(I also tried to using the loginStye: redirect instead of the popup which again works in the webapp but doesn't appear to do anything in electron and not firing any console errors)

**Comment by wojtkowiak** [comment] 2017-01-27 15:02
Hey,

sorry to keep you waiting, I will check that over the weekend. It is weird because until you would intentionaly block it in the `new-window` event it should work normally.

**Comment by wojtkowiak** [comment] 2017-02-08 20:09
FYI got a rough time now and it did not have time yet to test this, but do not worry it is still on my radar. I will investigate this on tomorrow.

**Comment by wojtkowiak** [comment] 2017-02-21 12:21
Ok, so I have reproduced this. Indeed something is wrong with [`window.open`](https://github.com/electron/electron/blob/master/docs/api/window-open.md) in Electron. I am checking if that is a bug I can file to Electron.

Apart from this problem, the are others. Next problem will be a little bit more complicated as google wants a redirect url to be provided without any wildcards. Meteor-desktop starts the app on a random port to prevent conflicts with other meteor-desktop apps. The solution would be to provide several urls with all possible ports but that seems to be an overkill.
Oh and the `accounts-google` is by default passing the meteor server url not the http://127.0.0.1:<port> on which meteor-desktop runs your app so that is another problem.

So... basically, `meteor-desktop` env resembles `cordova`. Given that meteor guide recommends using `Meteor.loginWith<externalService>` in Cordova I would advise you to do the same. Hope that is something you can consider.

Here is a gist that might be helpful: https://gist.github.com/yhagio/dcb24b7a74bd21d02838

I will make this problem something I will consider to fix in `1.x` but for now, I will not be able to do it as this would require some architectural changes.

**Comment by sferoze** [comment] 2017-05-22 02:43
@wojtkowiak I am using social login just like that gist but it does not work. In your last post are you referring to the gist as an alternative way to get social login to work with meteor-desktop? Or is social login not possible at all right now with meteor-desktop? 

I have disabled social login on desktop app but if there is an alternative way forward to get it working please let me know. I get the impression that it is currently not possible and will be fixed closer to 1.0 release. Thanks

**Comment by wojtkowiak** [comment] 2017-05-22 22:37
@sferoze well `Meteor.loginWith<externalService>` is normally supported in meteor so it should work. You can first try to get a working version in the browser normally running your app.
However I am not sure if the gist is 100% correct. Unfortunately I did not have to use any external login service yet in my desktop projects.  Are you getting any concrete error?

Have you tried to look for an another example of using that? You can also ask on the meteor forum for help with that. I can probably also help but I would need a small project prepared for working on that just to save some time on my side.

**Comment by sferoze** [comment] 2017-05-23 01:23
@wojtkowiak The social accounts package uses window.open to show a popup window. I get an error saying the popup window does not exist after trying to use Meteor.loginWithGoogle

I think there is an issue with electron and the popup window code it tries to use. I am just trying to use the standard meteor social login. 

I will prepare a small test repo with just social login and post back here.

**Comment by wojtkowiak** [comment] 2017-05-23 13:29
Well I did some digging and this seems to be much more complicated than I thought.
Actually what you probably need is a mix between:
https://www.npmjs.com/package/electron-google-oauth
https://github.com/sujith3g/meteor-g-plus

I would be very interested in providing that as a plugin to meteor-desktop but unfortunately I would not be able to collaborate much on that in the next two months.

**Comment by wojtkowiak** [comment] 2018-05-21 13:27
@sferoze @iamkevingreen did you manage to get through this issue or is this problem still standing?

**Comment by abduljanjua** [comment] 2018-12-18 10:50
Any improvements in this ?

**Closed** 2020-01-24 08:15 UTC
Labels: needs more info

**Comment by Ajaay** [comment] 2020-05-13 11:47
Hi @wojtkowiak ,

I'm working on this now to ad Azure Ad login to my app, but using the redirect style rather than pop-up. I have a woking setup in browser, but on Electron when I try and login nothing appears to happen on the app.

I see the following in the logs when I hit Meteor.loginWith<Service>

debug: [main] will-navigate event to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=bc222e34-89d1-412f-a069-7691d1800827&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2F_oauth%2FazureAd&scope=offline_access%20user.read&response_mode=query&state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJXdzlsNTl3a1BqTTNzbHFiR3RqMVdfX3NrX003aUVfTDVYUUFZRzFOanNzIiwiaXNDb3Jkb3ZhIjpmYWxzZSwicmVkaXJlY3RVcmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvbG9nZ2luZ0luIn0%3D&prompt=login&login_hint=alex.chapman%40candivue.com, assuming that this is HCP refresh

I ran a packet capture on my machine and this doesn't appear to trigger anything on the wire at all.

One thing to note is that I'm running a much older version of Meteor-desktop - 0.6.2 because there is a Chromium bug in the newer versions that I need to avoid.

Before I go down the rabbit hole of trying to fix that, I wondered if you had any theories as to what might be happening here?

Thanks!

**Comment by Ajaay** [comment] 2020-05-20 10:54
The issue described above went away after upgrading to meteor-desktop 2.2.5. 

I've now got the issue of invalid redirectUri but will work on figuring that out next
