### ISSUE TITLE
Hot Code Push

### ISSUE THREAD

**Issue by Wade-BuildOtto** [wojtkowiak/meteor-desktop#179] opened 2018-06-28 17:16 UTC
I have everything working but every change I make it keeps saying "skipping downloading current version" 

I have tried the settings in a few different ways but it doesn't want to get the latest bundle. 

It just doesn't pickup on the changes, I have to close and re-run each time. it closes and re-opens with every change. 

I am on meteor 1.7.0.3

**Comment by wojtkowiak** [comment] 2018-06-29 11:47
Hey,

can you post your logs from both `meteor --mobile-server=127.0.0.1:3000` and `npm run desktop` while having env var `METEOR_DESKTOP_DEBUG=1` set?

**Comment by Wade-BuildOtto** [comment] 2018-06-29 16:29
here you go. doesn't seem to say much.

**Meteor:**
found cacache@10.0.4 [required: 10.0.4]
[meteor-desktop] cache match
[meteor-desktop] preparing desktop.asar took: 351.331ms
[meteor-desktop] performance summary:
		whole build: 351ms
		basic deps lookout: 1ms
		deps get cacache: 0ms
		readdir: 336ms
		file add: 0ms


**desktop:**
verbose: [autoupdate] checking for updates on http://127.0.0.1:3000/
info: [autoupdate] [AssetBundleManager] trying to query http://127.0.0.1:3000/__cordova/manifest.json
debug: [autoupdate] [AssetManifest] 71 entries. (Version: 772c1b7ef219cd650ee1cc1460d6733ca4f8834f)
debug: [autoupdate] [AssetBundleManager] downloaded asset manifest for version: 772c1b7ef219cd650ee1cc1460d6733ca4f8834f
info: [autoupdate] skipping downloading current version: 772c1b7ef219cd650ee1cc1460d6733ca4f8834f

**Comment by wojtkowiak** [comment] 2018-07-06 09:18
Sorry for no updates. To be honest I did not have the time yet to fully test compatibility with `1.7`. Definitely there is something different probably due to introduction of `web.legacy` however during my quick test HCP was working ok.
I am currently on holidays so I will pick it up on Monday.

I will need some more info from you. I need full logs from desktop from the start (`npm run desktop`) till app startup. Then please make a change in the client code of your meteor project and once again catch full logs from meteor and desktop. After that make any change in `.desktop` and also post the logs. All of that with (METEOR_DESKTOP_DEBUG=1).

**Comment by met5678** [comment] 2018-07-16 03:55
I'm also seeing this issue -- hot reloads don't work at all. A code change causes the electron client to refresh but the new code isn't loaded. It just shows the original version you started desktop with. You have to restart the electron client using `npm run desktop` again to get the new version. Tested with the logs you mentioned, and here are my results:

Context: fresh app, created with:
```
meteor create client-app-normal
cd client-app-normal
meteor add-platform ios
meteor npm install --save-dev meteor-desktop
npm run desktop -- init
```

Meteor, startup:
```
AndrewsMacBookPro:client-app-normal andrew$ METEOR_DESKTOP_DEBUG=1 meteor --mobile-server=127.0.0.1:3000
[[[[[ ~/dev/goddess/video-goddess/client-app-normal ]]]]]

=> Started proxy.                             
found cacache@10.0.4 [required: 10.0.4]      |
[meteor-desktop] cache matchga:meteor-de...  |
[meteor-desktop] preparing desktop.asar took: 221.318ms
[meteor-desktop] performance summary:
		whole build: 222ms
		basic deps lookout: 164ms
		deps get cacache: 120ms
		readdir: 7ms
		file add: 1ms
=> Started MongoDB.                           
I20180715-23:50:25.406(-4)? [meteor-desktop] watching /Users/andrew/dev/goddess/video-goddess/client-app-normal/.desktop for changes.
=> Started your app.

=> App running at: http://localhost:3000/
```

Desktop, startup:
```
> client-app-normal@ desktop /Users/andrew/dev/goddess/video-goddess/client-app-normal
> meteor-desktop

METEOR-DESKTOP v1.5.0

REMINDER: your Meteor project should be running now on port 3000

INFO  index:  initializing
INFO  electronApp:  scaffolding
VERBOSE  desktop:  checking .desktop existence
VERBOSE  meteorApp:  updating .meteor/.gitignore
VERBOSE  meteorApp:  desktopHCP is enabled, checking for required packages
VERBOSE  electronAppScaffold:  clearing desktop-build
VERBOSE  electronAppScaffold:  creating /Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build/app
VERBOSE  electronAppScaffold:  copying skeleton app
VERBOSE  electronAppScaffold:  writing package.json
VERBOSE  electronApp:  updating package.json fields
DEBUG  electronApp:  writing updated package.json
INFO  electronApp:  updating list of package.json's dependencies
DEBUG  electronApp:  merging settings.json[dependencies]
DEBUG  electronApp:  merging settings.json[plugins]
DEBUG  electronApp:  merging dependencies from modules
DEBUG  electronApp:  writing updated package.json
VERBOSE  electronApp:  calculating compatibility version
DEBUG  electronApp:  meteor-desktop compatibility version is  1
DEBUG  electronApp:  .desktop compatibility version is  0
DEBUG  electronApp:  compatibility version calculated from ["connect:3.6.5","devtron:1.4.0","electron-debug:1.5.0","find-port:2.0.1","fs-extra:3.0.1","fs-plus:2.9.3","lodash:4.17.10","meteor-desktop-splash-screen:0.4.3","mime:2.0.3","queue:4.0.1","reify:0.15.1","request:2.79.0","rimraf:2.6.2","send:0.16.1","server-destroy:1.0.1","shelljs:0.7.5","winston:2.3.0","meteor-desktop:1","desktop-app:0"]
INFO  electronApp:  issuing node_modules install from electron-builder
VERBOSE  electronApp:  rebuilding for x64
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch x64
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build
INFO  electronApp:  issuing native modules rebuild from electron-builder
VERBOSE  electronApp:  rebuilding for x64
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch x64
  • no native production dependencies
VERBOSE  electronApp:  copying .desktop to temporary location
DEBUG  electronApp:  updating settings.json fields
INFO  desktop:  calculating hash version from .desktop contents
VERBOSE  desktop:  calculated .desktop hash version is 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9
INFO  electronApp:  excluding files from packing
INFO  electronApp:  transpiling and uglifying
INFO  electronApp:  packing .desktop to asar
VERBOSE  electronApp:  clearing temporary .desktop
INFO  meteorApp:  checking for any mobile platform
INFO  meteorApp:  building meteor app
DEBUG  meteorApp:  clearing build dir
INFO  meteorApp:  acquiring index.html
(node:15939) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
INFO  meteorApp:  successfully downloaded index.html from running meteor app
VERBOSE  meteorApp:  copying mobile build
INFO  meteorApp:  acquiring manifest.json
INFO  meteorApp:  successfully downloaded manifest.json from running meteor app
INFO  meteorApp:  mobile build copied to electron app
DEBUG  meteorApp:  copy cordova.js to meteor build
INFO  meteorApp:  injecting isDesktop
INFO  meteorApp:  injected successfully
INFO  meteorApp:  packing meteor app to asar archive
VERBOSE  meteorApp:  clearing meteor app after packing
INFO  meteorApp:  meteor build finished
INFO  electronApp:  running
info: [main] app data dir is: /Users/andrew/Library/Application Support/MyMeteorApp
info: [main] initial desktop version is  91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev
info: [main] will use desktop.asar from initial version because the initial version of meteor app has changed: /Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build/desktop.asar
debug: [main] skeleton version 1.5.0
info: [main] ready fired
info: [main] seting autoupdate feed to url: http://127.0.0.1/update/darwin_x64/0.0.1
info: [main] disabling autoUpdate because on Mac in development build it would not work anyway (app needs to be signed)
debug: [main] loading plugin: meteor-desktop-splash-screen
info: [meteor-desktop-splash-screen] [splashScreenHtml] preparing splash screen
info: [meteor-desktop-splash-screen] [splashScreenHtml] splash screen prepared
info: [meteor-desktop-splash-screen] [splashWindow] displaying splash screen from file:///Users/andrew/Library/Application Support/MyMeteorApp/splash.html
2018-07-15 23:51:29.658 Electron[15941:3138975] *** WARNING: Textured window <AtomNSWindow: 0x7fe6d5592900> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
info: [meteor-desktop-splash-screen] [updateScreenHtml] preparing splash screen
info: [meteor-desktop-splash-screen] [updateScreenHtml] splash screen prepared
debug: [main] loading internal module: autoupdate
debug: [main] loading internal module: dummy
debug: [main] loading internal module: localServer
info: [localServer] last used port is 57200
debug: [main] loading internal module: storageMigration
debug: [main] loading module: example => example
verbose: [autoupdate] initializing autoupdate module
verbose: [autoupdate] trying to read initial bundle version
verbose: [autoupdate] [AssetBundle] making bundle object for /Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build/meteor.asar
verbose: [autoupdate] [AssetBundle] loading manifest from /Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build/meteor.asar
debug: [autoupdate] [AssetManifest] 71 entries. (Version: 0415c858635d4f9564bfaa1ce1fa7a0c50db0db8)
verbose: [autoupdate] [AssetBundle] trying to read desktop version for 0415c858635d4f9564bfaa1ce1fa7a0c50db0db8
verbose: [autoupdate] [AssetBundle] the desktop version is 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev
info: [autoupdate] detected new bundled version, removing versions directory if it exists
info: [autoupdate] created versions dir
verbose: [autoupdate] using initial asset bundle
debug: [main] desktop loaded
debug: [storageMigration] newest storage (Local Storage) entry is null
info: [localServer] will serve from:  /Users/andrew/dev/goddess/video-goddess/client-app-normal/.meteor/desktop-build/meteor.asar
info: [localServer] assigned port 57200
verbose: [autoupdate] started startup timer
debug: [autoupdate] timer set to 60000
debug: [main] protocol meteor:// registered
debug: [main] opening meteor://desktop
verbose: [meteor-desktop-splash-screen] [splashWindow] enabling click through
2018-07-15 23:51:30.763 Electron Helper[15945:3139078] Couldn't set selectedTextBackgroundColor from default ()
2018-07-15 23:51:30.825 Electron Helper[15943:3139045] Couldn't set selectedTextBackgroundColor from default ()
verbose: [autoupdate] startup did complete, stopping startup timer (startup took 882ms)
info: [main] assuming meteor webapp has loaded
startup took: 1335.251ms
debug: [main] showing main window
debug: [main] received did-stop-loading
info: [main] assuming meteor webapp has loaded
debug: [main] window already loaded
```

Meteor, after change:
```
found cacache@10.0.4 [required: 10.0.4]
[meteor-desktop] cache match
[meteor-desktop] preparing desktop.asar took: 150.642ms
[meteor-desktop] performance summary:
		whole build: 151ms
		basic deps lookout: 0ms
		deps get cacache: 0ms
		readdir: 145ms
		file add: 0ms
=> Client modified -- refreshing
```

Desktop, after change:
```
verbose: [autoupdate] checking for updates on http://127.0.0.1:3000/
info: [autoupdate] [AssetBundleManager] trying to query http://127.0.0.1:3000/__cordova/manifest.json
debug: [autoupdate] [AssetManifest] 71 entries. (Version: fe594f4cba24c57eca25118c7e125074844b6160)
debug: [autoupdate] [AssetBundleManager] downloaded asset manifest for version: fe594f4cba24c57eca25118c7e125074844b6160
debug: [autoupdate] got desktop version information: 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev (compatibility: d4ea78ce7a055c178ee55451a47d56aa)
info: [autoupdate] [AssetBundleManager] created download dir.
debug: [autoupdate] [AssetBundleManager] manifest copied to new Download dir
verbose: [autoupdate] [AssetBundle] making bundle object for /Users/andrew/Library/Application Support/MyMeteorApp/versions/Downloading
debug: [autoupdate] [AssetBundle] the desktop version was provided by constructor and is 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev
debug: [autoupdate] [AssetBundleDownloader] downloader created for /Users/andrew/Library/Application Support/MyMeteorApp/versions/Downloading
verbose: [autoupdate] [AssetBundleDownloader] started downloading assets from bundle with version: fe594f4cba24c57eca25118c7e125074844b6160
verbose: [autoupdate] [AssetBundleDownloader] saving /__cordova/app/app.js
verbose: [autoupdate] [AssetBundleDownloader] saving /__cordova/app/333c93fd0e197146c23e13678c5debe5cd32f30d.map
verbose: [autoupdate] [AssetBundleDownloader] saving /
verbose: [autoupdate] [AssetBundleDownloader] finished downloading new asset bundle version:fe594f4cba24c57eca25118c7e125074844b6160
verbose: [autoupdate] setting last downloaded and pending version as fe594f4cba24c57eca25118c7e125074844b6160
debug: [main] received newVersionReady (desktop update present)
debug: [main] will-navigate event to meteor://desktop/, assuming that this is HCP refresh
verbose: [main] entering update to new HCP version procedure
verbose: [main] 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev !== 91866e4ca31d8d67a9daa3ad41ac9bbb97deaad9_dev
info: [meteor-desktop-splash-screen] [updateWindow] displaying splash screen from file:///Users/andrew/Library/Application Support/MyMeteorApp/update.html
debug: [main] firing onReset from autoupdate
info: [autoupdate] serving asset bundle with version: fe594f4cba24c57eca25118c7e125074844b6160
verbose: [autoupdate] started startup timer
debug: [autoupdate] timer set to 60000
debug: [main] resetting local server
info: [localServer] will serve from:  /Users/andrew/Library/Application Support/MyMeteorApp/versions/fe594f4cba24c57eca25118c7e125074844b6160
info: [localServer] assigned port 57200
verbose: [autoupdate] startup did complete, stopping startup timer (startup took 591ms)
info: [main] assuming meteor webapp has loaded
debug: [main] window already loaded
debug: [main] received did-stop-loading
info: [main] assuming meteor webapp has loaded
debug: [main] window already loaded
verbose: [autoupdate] checking for updates on http://127.0.0.1:3000/
info: [autoupdate] [AssetBundleManager] trying to query http://127.0.0.1:3000/__cordova/manifest.json
debug: [autoupdate] [AssetManifest] 71 entries. (Version: fe594f4cba24c57eca25118c7e125074844b6160)
debug: [autoupdate] [AssetBundleManager] downloaded asset manifest for version: fe594f4cba24c57eca25118c7e125074844b6160
info: [autoupdate] skipping downloading current version: fe594f4cba24c57eca25118c7e125074844b6160
2018-07-15 23:52:34.126 Electron Helper[15964:3139904] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by met5678** [comment] 2018-07-16 03:56
Appreciate all the work you do on this btw @wojtkowiak -- wish I had the know-how to diagnose this one more deeploy.

**Comment by met5678** [comment] 2018-07-16 12:19
Correct, Meteor 1.7.0.3 and and meteor-desktop 1.5.0

**Comment by wojtkowiak** [comment] 2018-07-20 15:51
Confirmed, ugly bug on my side, big sorry for that.
Fix is coming in `1.6.0` soon.

**Comment by met5678** [comment] 2018-07-21 03:37
No problem, thanks for fixing quick! Excited to get it running.

**Comment by wojtkowiak** [comment] 2018-07-28 09:59
`1.6.0` is out, should be fixed. Please let know when you'll have the time to check it.

**Comment by andrew-luminal** [comment] 2018-07-30 14:43
Testing this tomorrow night, apologies for the delay!

**Comment by AndyNormore** [comment] 2019-05-22 20:47
Hrmm not so sure about closing. I have a desktop app that is on Meteor 1.8.1 and it's not behaving. I've pushed an update to the server, web client updates -- desktop is still the older one.

**Comment by wojtkowiak** [comment] 2020-01-24 11:19
Closing this, @AndyNormore if you still experience this problem please file a new issue.

**Closed by wojtkowiak** 2020-01-24 11:19 UTC
Labels: bug, skeleton app
